version: "3.7"

services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    init: true
    ports:
      - 9200:9200
    environment: 
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks: 
      - es-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    init: true
    depends_on:
      - elasticsearch
    ports: 
      - 5601:5601
    networks: 
      - es-network

networks: 
  es-network:
    driver: bridge
