version: "3.7"

services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    init: true
    ports:
      - 9200:9200
    environment: 
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks: 
      - es-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.3.0
    init: true
    depends_on: 
      - elasticsearch
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./mariadb-java-client-2.4.2.jar:/usr/share/logstash/logstash-core/lib/jars/mariadb-java-client-2.4.2.jar:ro
    networks:
      - es-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    init: true
    depends_on:
      - logstash
    ports: 
      - 5601:5601
    networks: 
      - es-network

networks: 
  es-network:
    driver: bridge
